name: Build and Deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Compile LaTeX
              uses: ./.github/actions/compile

            - name: Move PDFs to Folder
              run: |
                  mkdir build
                  mv *.pdf build/

            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./build/

            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
