name: Build and Deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build_pdfs:
        uses: ./.github/workflows/build.yml
    trigger_deployment:
        needs: build_pdfs
        runs-on: ubuntu-latest
        steps:
            - name: Trigger orbisat-oeiras.github.io deployment
              run: |
                  curl -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.PAGES_REPO_TOKEN }}" \
                    https://api.github.com/repos/orbisat-oeiras/orbisat-oeiras.github.com/dispatches \
                    -d '{"event_type": "orbipacket-deploy"}'
